name: CI .NET

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Installer .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restaurer les packages
      run: dotnet restore

    - name: Compiler la solution
      run: dotnet build --configuration Release --no-restore

    - name: Ex√©cuter les tests
      run: dotnet test --configuration Release --no-build

    - name: Publier l'API
      run: dotnet publish Api/Api.csproj -c Release -o publish

    - name: Upload de l'artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-net7
        path: publish
